detect test failures in CI job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -112,16 +112,18 @@ jobs:
             run_tests
 
       - name: Download requested Godot version for testing
-        if: matrix.target.run_tests
+        if: ${{ matrix.target.run_tests && matrix.target-type == 'editor' }}
         run: |
           wget "https://github.com/godotengine/godot-builds/releases/download/${GODOT_TEST_VERSION}/Godot_v${GODOT_TEST_VERSION}_linux.x86_64.zip" -O Godot.zip
           unzip -a Godot.zip
           chmod +x "Godot_v${GODOT_TEST_VERSION}_linux.x86_64"
           echo "GODOT=$(pwd)/Godot_v${GODOT_TEST_VERSION}_linux.x86_64" >> $GITHUB_ENV
 
+      # run tests on the editor builds
       - name: Run GDScript tests
-        if: matrix.target.run_tests
+        if: ${{ matrix.target.run_tests && matrix.target-type == 'editor' }}
         run: |
+          set -x
           $GODOT --headless --version
 
           # link the dll over into lib so we can run the tests
@@ -129,10 +131,25 @@ jobs:
               ln -sv $(pwd)/bin/* demo/addons/hex_map/lib/
           # workaround for https://github.com/bitwes/Gut/issues/589, create the
           # .godot directory so GUT can find GutUtils
-          (cd demo && (timeout 30 $GODOT --import --headless >/dev/null 2>&1 || true))
+          (cd demo &&
+              (timeout 30 $GODOT --import --headless >/dev/null 2>&1 || true))
 
-          # actually run the tests
-          $GODOT --headless -s addons/gut/gut_cmdln.gd -d --path ./demo
+          # actually run the tests, we need to save the output to check for
+          # test failures
+          $GODOT --headless -s addons/gut/gut_cmdln.gd --path ./demo 2>&1 |
+              tee test-output.txt
+
+          # check for failing tests
+          if grep -qE -- "---- [0-9]+ failing tests ----" test-output.txt; then
+            exit 1
+          fi
+
+          # check for script errors
+          if grep -EC 3 -- "SCRIPT ERROR:" test-output.txt; then
+            echo "*** Tests failed due to script errors***"
+            exit 1
+          fi
+
           # cd test
           # # Need to run the editor so .godot is generated... but it crashes! Ignore that :-)
           # (cd project && (timeout 30 $GODOT --import --headless >/dev/null 2>&1 || true))
